server:
  port: 8086

spring:
  application:
    name: mission-service


  datasource:
    url: jdbc:postgresql://ep-little-sky-ai5kiu27-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_OHu1ViXpNQ9o
    driver-class-name: org.postgresql.Driver

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # rabbitmq
  rabbitmq:
    host: moose.rmq.cloudamqp.com
    port: 5672
    username: dkptazsn
    password: 8nA0q8-i2hUnq2ET1vDAXYq3-V1rIqEu
    virtual-host: dkptazsn

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
  packages-to-scan: com.disa.mission_service
  paths-to-match: /api/**
  default-flat-param-object: true