server:
  port: ${SERVER_PORT:8086}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: mission-service


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # rabbitmq
  rabbitmq:
    host: ${RABBITMQ_HOST:moose.rmq.cloudamqp.com}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:dkptazsn}
    password: ${RABBITMQ_PASSWORD:8nA0q8-i2hUnq2ET1vDAXYq3-V1rIqEu}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:dkptazsn}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
  packages-to-scan: com.disa.mission_service
  paths-to-match: /api/**
  default-flat-param-object: true