spring:
  application:
    name: personnel-service
  datasource:
    url: jdbc:postgresql://localhost:5432/personnel_service
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
