spring:
  application:
    name: personnel-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:personnel_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: update

external:
  task:
    api:
      url: ${TASK_API_URL:https://api.example.com}
      token: ${TASK_API_TOKEN:your_api_token_here}

model:
  gemini:
    api:
      url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent}
      key: ${GEMINI_API_KEY}
